# These are supported funding model platforms

patreon: stunning_munda # Replace with a single Patreon username
ko_fi: flyingpython # Replace with a single Ko-fi username
community_bridge: flyingpython # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: FlyingPython # Replace with a single Liberapay username
issuehunt: reybotdev # Replace with a single IssueHunt username
custom: https://buymeacoffee.com/duelist # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
